# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=phuy
      - POSTGRES_PASSWORD=4rAM6H3DqTFH86n6
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres:
